### PR TITLE
Fix typescript types (adds support for Mongoose 6)

### LINKED ISSUE #157: Support for Mongoose 6
Mongoose 6 has some breaking changes, so we need to safely migrate to mongoose 6.

### PR DESCRIPTION
**Pull request by kerolloz**
fixes #157

### CODE REVIEW

**Comment by kerolloz** [comment]
These errors are fixed now ✅ 
image

**Comment by aravindnc** [comment]
@kerolloz Awesome Thanks!.

**Comment by kerolloz** [comment]
@aravindnc When will it be published on NPM? 🤔

**Comment by aravindnc** [comment]
@kerolloz Did just now v1.6.3. Please take a look.

**Comment by kerolloz** [comment]
Thank you ✨ @aravindnc

**Pull request merged**
