### PR TITLE
Bugfix for document count with collation

### PR DESCRIPTION
**Pull request by lingo**
Fixes issues where no results or incorrect count are returned when using collations.

Fix thanks to https://github.com/ingvarr6

https://github.com/aravindnc/mongoose-paginate-v2/issues/13
https://github.com/aravindnc/mongoose-paginate-v2/issues/39

### CODE REVIEW

**Comment by aravindnc** [comment]
@lingo Published. Thanks.

**Comment by prerna-su** [comment]
@lingo @aravindnc : This is breaking for mongo version below 3.4 as collation is not supported.

**Comment by aravindnc** [comment]
@prerna-su Sorry to hear. Please use v1.3.14 until some patch is added.

**Comment by aravindnc** [comment]
@prerna-su New patch has been added, please update the package to v1.3.16 Let me know if it fixes your issue.

**Pull request merged**
